---
- name: Install and configure LazyVim
  hosts: all
  become: true
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    lazyvim_user: "{{ lookup('env', 'USER') }}"
    neovim_src_dir: /opt/neovim
    repositories_dir: "{{ home_dir }}/repositories"
    dotfiles_repo: "https://github.com/runyanjake/dotfiles.git"
    dotfiles_dir: "{{ repositories_dir }}/dotfiles"
    nvim_config_dir: "{{ home_dir }}/.config/nvim"

  tasks:
    - name: Install required packages for building Neovim and clipboard support
      apt:
        name:
          - build-essential
          - cmake
          - unzip
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - pkg-config
          - curl
          - doxygen
          - xclip
          - xsel
          - fonts-powerline
          - fonts-firacode
        state: present
        update_cache: yes

    - name: Download Nerd Font (FiraCode Nerd Font) to /usr/local/share/fonts
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        dest: /tmp/FiraCode.zip
        mode: '0644'

    - name: Unzip Nerd Font into fonts directory
      unarchive:
        src: /tmp/FiraCode.zip
        dest: /usr/local/share/fonts/
        remote_src: yes
      notify: Rebuild font cache

    - name: Ensure Neovim source directory exists
      file:
        path: "{{ neovim_src_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Clone or update Neovim repository
      git:
        repo: https://github.com/neovim/neovim.git
        dest: "{{ neovim_src_dir }}"
        version: stable
        update: yes
        force: yes
        accept_hostkey: yes

    - name: Check if Neovim is already installed
      stat:
        path: /usr/local/bin/nvim
      register: nvim_stat

    - name: Clean old Neovim build files
      command: git clean -fdx
      args:
        chdir: "{{ neovim_src_dir }}"
      when: not nvim_stat.stat.exists

    - name: Build Neovim from source
      command: make CMAKE_BUILD_TYPE=RelWithDebInfo
      args:
        chdir: "{{ neovim_src_dir }}"
      environment:
        MAKEFLAGS: "-j{{ ansible_processor_vcpus | default(2) }}"
      when: not nvim_stat.stat.exists

    - name: Install Neovim
      command: make install
      args:
        chdir: "{{ neovim_src_dir }}"
      when: not nvim_stat.stat.exists

    # ---- USER TASKS BELOW (no sudo!) ----

    - name: Create repositories directory in user home
      become: false
      file:
        path: "{{ repositories_dir }}"
        state: directory
        mode: '0755'

    - name: Clone or update dotfiles repository
      become: false
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        update: yes
        force: yes
        accept_hostkey: yes

    - name: Ensure Neovim config directory exists
      become: false
      file:
        path: "{{ nvim_config_dir }}"
        state: directory
        mode: '0755'

    - name: Symlink LazyVim config files
      become: false
      file:
        src: "{{ dotfiles_dir }}/lazyvim/{{ item.src }}"
        dest: "{{ nvim_config_dir }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: "stylua.toml", dest: "stylua.toml" }
        - { src: "lua",        dest: "lua" }
        - { src: "init.lua",   dest: "init.lua" }
        - { src: "lazyvim.json", dest: "lazyvim.json" }

  handlers:
    - name: Rebuild font cache
      command: fc-cache -f -v

