---
- name: Install and Configure Software Packages
  hosts: all
  become: true

  tasks:
    - name: Ensure base dependencies are installed
      ansible.builtin.apt:
        name:
          - snapd
          - apt-transport-https
        state: present
        update_cache: yes

    # --- Individual Snap Package Installations ---

    - name: Install nordvpn
      community.general.snap:
        name: nordvpn
        state: present
        classic: yes

    - name: Install steam
      community.general.snap:
        name: steam
        state: present
        classic: yes

    - name: Enable i386 architecture for Steam
      ansible.builtin.command: dpkg --add-architecture i386
      args:
        creates: /etc/dpkg/dpkg.cfg.d/multiarch
      notify: Update apt cache

    - name: Install 32-bit NVIDIA drivers for Steam
      ansible.builtin.apt:
        name: libnvidia-gl-580:i386 # Make sure this version is correct for your driver
        state: present

    - name: Install sublime-text
      community.general.snap:
        name: sublime-text
        state: present
        classic: yes

    - name: Install obs-studio
      community.general.snap:
        name: obs-studio
        state: present

    - name: Install vlc
      community.general.snap:
        name: vlc
        state: present

    - name: Install gimp
      community.general.snap:
        name: gimp
        state: present

    - name: Install darktable
      community.general.snap:
        name: darktable
        state: present

    - name: Install discord
      community.general.snap:
        name: discord
        state: present

    - name: Install spotify
      community.general.snap:
        name: spotify
        state: present

  # Handlers are only run if notified by a task
  handlers:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
