---
- name: Install base packages
  hosts: all
  become: true
  vars:
    base_packages:
      - build-essential
      - curl
      - wget
      - git
      - unzip
      - zip
      - htop
      - tree
      - tmux
      - ca-certificates
      - software-properties-common
      - gnupg
      - lsb-release
      - gh 
      - python3

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      apt:
        name: "{{ base_packages }}"
        state: present

